"""add donor query indexes

Revision ID: 940dd10ee66b
Revises: 8ab52cb6ab59
Create Date: 2026-09-14 11:11:10.374603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940dd10ee66b'
down_revision: Union[str, Sequence[str], None] = '8ab52cb6ab59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_donors_availability', 'donors', ['availability'], unique=False)
    op.create_index('ix_donors_blood_group', 'donors', ['blood_group'], unique=False)
    op.create_index('ix_donors_city', 'donors', ['city'], unique=False)
    op.create_index('ix_donors_is_active', 'donors', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_donors_is_active', table_name='donors')
    op.drop_index('ix_donors_city', table_name='donors')
    op.drop_index('ix_donors_blood_group', table_name='donors')
    op.drop_index('ix_donors_availability', table_name='donors')
    op.create_index(op.f('idx_donors_blood_group'), 'donors', ['blood_group'], unique=False)
    op.create_index(op.f('idx_donors_availability'), 'donors', ['availability'], unique=False)
    op.create_index(op.f('idx_blood_requests_status'), 'blood_requests', ['status'], unique=False)
    op.create_index(op.f('idx_blood_requests_blood_group'), 'blood_requests', ['blood_group'], unique=False)
    # ### end Alembic commands ###
